/**
 * @fileoverview ESLint 9 flat config for realm-ascension (Elysian Cathedral
 * PRD build). Layers:
 *   - JS + TS recommended
 *   - React Hooks (flat config recommended-latest)
 *   - jsx-a11y (flat recommended)
 *   - Local `hc` plugin with the `no-inline-framer-transition` rule
 *
 * The custom rule enforces PRD A-5 / motion.md §1 — motion transitions live
 * in a shared variants module. See tools/eslint-rules/ for the rule source.
 */

import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import reactHooks from 'eslint-plugin-react-hooks';
import jsxA11y from 'eslint-plugin-jsx-a11y';
import globals from 'globals';

import hcPlugin from './tools/eslint-rules/index.js';

export default [
  // ---------------------------------------------------------------------------
  // Global ignores. Keep this first so plugins/parsers don't waste cycles on
  // generated or vendored content.
  // ---------------------------------------------------------------------------
  {
    ignores: [
      'dist/**',
      'build/**',
      'coverage/**',
      'node_modules/**',
      '.beads/**',
      '.claude/**',
      '.brainstorm/**',
      // Gas City local runtime/overlay state (gitignored, not project source).
      '.gc/**',
      'public/**',
      // Generated by Vite/PWA during build.
      'dev-dist/**',
      // Prettier and format artifacts.
      '*.min.js',
    ],
  },

  // ---------------------------------------------------------------------------
  // Baseline: JavaScript recommended.
  // ---------------------------------------------------------------------------
  js.configs.recommended,

  // ---------------------------------------------------------------------------
  // TypeScript recommended (no type-aware rules — keep lint fast; typecheck
  // job covers the type correctness pass).
  // ---------------------------------------------------------------------------
  ...tseslint.configs.recommended,

  // ---------------------------------------------------------------------------
  // jsx-a11y recommended (flat config export).
  // ---------------------------------------------------------------------------
  jsxA11y.flatConfigs.recommended,

  // ---------------------------------------------------------------------------
  // react-hooks recommended (flat config). The plugin's
  // `recommended-latest` export is the ESLint 9 / flat-compatible entry.
  // ---------------------------------------------------------------------------
  reactHooks.configs['recommended-latest'],

  // ---------------------------------------------------------------------------
  // Project-wide defaults for source files: languageOptions, globals, and
  // the local `hc` plugin registration.
  // ---------------------------------------------------------------------------
  {
    files: ['src/**/*.{ts,tsx,js,jsx}'],
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      parserOptions: {
        ecmaFeatures: { jsx: true },
      },
      globals: {
        ...globals.browser,
      },
    },
    plugins: {
      hc: hcPlugin,
    },
    rules: {
      'hc/no-inline-framer-transition': 'error',
      // Allow non-breaking spaces (U+00A0) inside template literals so
      // effect-text rendering can keep `+5 [icon]` from line-wrapping
      // between number and trailing icon. NBSP outside strings is still
      // flagged.
      'no-irregular-whitespace': ['error', { skipTemplates: true }],
      // ppf9.4.1 schema gate: every passive-firing site must read through
      // getPassives() in src/data/cardPassives.ts so dual-behaviour items
      // (Card.passive second-slot) are honored. Override list below
      // exempts the accessor itself + the render-policy site (pending
      // ppf9.4.4 migration) + tests.
      'hc/no-raw-item-passive-read': 'error',

      // Relax a handful of noisy defaults so this gate focuses on correctness
      // + the custom motion discipline rule. The typecheck job enforces
      // stricter type-level guarantees separately.
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/no-unused-vars': [
        'warn',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^_' },
      ],
      '@typescript-eslint/no-empty-object-type': 'off',
      '@typescript-eslint/no-unused-expressions': 'off',
      'no-empty': ['error', { allowEmptyCatch: true }],
      // React 19 + TSX: we control our own key semantics and sometimes use
      // inert aria on decorative elements — let jsx-a11y defaults stand
      // except for a few that collide with our component patterns.
      'jsx-a11y/no-autofocus': 'off',
      'jsx-a11y/click-events-have-key-events': 'off',
      'jsx-a11y/no-static-element-interactions': 'off',
      'jsx-a11y/no-noninteractive-element-interactions': 'off',
      'jsx-a11y/label-has-associated-control': 'off',
    },
  },

  // ---------------------------------------------------------------------------
  // Tests: allow a broader set of patterns.
  // ---------------------------------------------------------------------------
  {
    files: ['src/**/*.{test,spec}.{ts,tsx,js,jsx}', 'src/**/__tests__/**'],
    languageOptions: {
      globals: {
        ...globals.browser,
        ...globals.node,
      },
    },
    rules: {
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/no-non-null-assertion': 'off',
      // ppf9.4.1: tests authoring fixtures or asserting catalog-level
      // invariants (e.g. cards.test.ts validating that every 4uyn id
      // resolves to an item-passive) need the raw discriminator read.
      'hc/no-raw-item-passive-read': 'off',
    },
  },

  // ---------------------------------------------------------------------------
  // Scripts and build tooling — Node environment.
  // ---------------------------------------------------------------------------
  {
    files: ['scripts/**/*.{js,mjs,ts}', 'tools/**/*.{js,mjs,ts}', '*.config.{js,mjs,ts}'],
    languageOptions: {
      globals: {
        ...globals.node,
      },
    },
    rules: {
      '@typescript-eslint/no-unused-vars': 'off',
      'no-unused-vars': 'off',
    },
  },

  // ---------------------------------------------------------------------------
  // CommonJS config files (.cjs) — stylelint, prettier, etc. use module.exports.
  // ---------------------------------------------------------------------------
  {
    files: ['**/*.cjs'],
    languageOptions: {
      sourceType: 'commonjs',
      globals: {
        ...globals.node,
        ...globals.commonjs,
      },
    },
  },

  // ---------------------------------------------------------------------------
  // Narrow override: allowlist pre-existing inline `transition={{...}}` in
  // ChestReveal.tsx. See PRD R-22 / A-5' — V-9 consolidates Framer motion
  // transitions into src/motion/variants.ts. Remove this override when V-9
  // lands. TODO(PRD-V-9): hoist transition to shared variants module.
  // ---------------------------------------------------------------------------
  {
    files: ['src/ui/ChestReveal.tsx'],
    rules: {
      'hc/no-inline-framer-transition': 'off',
    },
  },

  // ---------------------------------------------------------------------------
  // ppf9.4.1 narrow override: the accessor itself (cardPassives.ts) MUST
  // perform the raw discriminator read — that's its job. The render-policy
  // site effectText.tsx was previously exempted while the legacy
  // `card.effects.kind === 'item-passive'` branch lived there; ppf9.4.4
  // migrated that read to `getPassives(card)`, so the effectText.tsx
  // exemption is no longer required.
  // ---------------------------------------------------------------------------
  {
    files: ['src/data/cardPassives.ts'],
    rules: {
      'hc/no-raw-item-passive-read': 'off',
    },
  },
];
