import type { SilhouetteTemplate } from '../schema';

export const HERO_TEMPLATES: SilhouetteTemplate[] = [
  {
    id: 'hero_warrior_upright',
    archetype: 'hero',
    subtype: 'warrior',
    description: 'Tall upright champion with centered weapon and plated silhouette.',
    poseRead: 'upright',
    symmetry: 'high',
    shapeLanguage: ['vertical', 'shielded torso', 'blade axis', 'pauldron wedges'],
    anchors: [
      { id: 'head', x: 12, y: 6 },
      { id: 'torso', x: 12, y: 12 },
      { id: 'weapon', x: 12, y: 14 },
      { id: 'halo', x: 12, y: 5 },
    ],
    basePaths: ['head-helm', 'torso-plate', 'weapon-vertical', 'lower-robes-or-greaves'],
    focalZones: ['face/helm', 'weapon jewel', 'chest crest'],
    forbiddenFeatures: ['tiny facial detail', 'naturalistic anatomy', 'busy cloth folds'],
  },
  {
    id: 'hero_sentinel_shield',
    archetype: 'hero',
    subtype: 'sentinel',
    description: 'Broad, stable hero with shield-forward composition.',
    poseRead: 'upright',
    symmetry: 'high',
    shapeLanguage: ['broad shield', 'stable base', 'protective arc'],
    anchors: [
      { id: 'head', x: 12, y: 6 },
      { id: 'shield', x: 12, y: 13 },
      { id: 'halo', x: 12, y: 5 },
    ],
    basePaths: ['head-helm', 'shield-large', 'shoulder-frame', 'lower-tabard'],
    focalZones: ['shield crest', 'helm slit', 'shield jewel'],
    forbiddenFeatures: ['excess weaponry', 'off-balance stance'],
  },
  {
    id: 'hero_rogue_cloak',
    archetype: 'hero',
    subtype: 'rogue',
    description: 'Slim cloaked figure with elegant asymmetry and stealth emphasis.',
    poseRead: 'forward-leaning',
    symmetry: 'medium',
    shapeLanguage: ['hood arc', 'cloak diagonal', 'dagger or short blade', 'narrow torso'],
    anchors: [
      { id: 'head', x: 12, y: 7 },
      { id: 'cloak', x: 10, y: 13 },
      { id: 'weapon', x: 14, y: 14 },
      { id: 'halo', x: 12, y: 6 },
    ],
    basePaths: ['hood', 'cloak-sweep', 'arm/weapon', 'torso-core'],
    focalZones: ['hood opening', 'weapon highlight', 'belt gem'],
    forbiddenFeatures: ['hyper-detailed face', 'too many accessory shapes'],
  },
  {
    id: 'hero_sage_halo',
    archetype: 'hero',
    subtype: 'sage',
    description: 'Mystic figure with strong circular aura and calmer internal geometry.',
    poseRead: 'regal',
    symmetry: 'high',
    shapeLanguage: ['halo circle', 'staff or open hands', 'layered robes'],
    anchors: [
      { id: 'head', x: 12, y: 7 },
      { id: 'halo', x: 12, y: 7 },
      { id: 'torso', x: 12, y: 13 },
    ],
    basePaths: ['halo-ring', 'head', 'robe-body', 'staff-or-glyph'],
    focalZones: ['halo', 'face silhouette', 'staff jewel'],
    forbiddenFeatures: ['weapon-heavy read', 'tight aggressive angles'],
  },
  {
    id: 'hero_ranger_bow',
    archetype: 'hero',
    subtype: 'ranger',
    description: 'Elegant silhouette with bow arc framing the figure.',
    poseRead: 'upright',
    symmetry: 'medium',
    shapeLanguage: ['bow curve', 'cloak taper', 'focused stance'],
    anchors: [
      { id: 'head', x: 12, y: 7 },
      { id: 'bow', x: 16, y: 12 },
      { id: 'torso', x: 11, y: 13 },
    ],
    basePaths: ['head-profile', 'torso', 'bow-arc', 'cloak-lower'],
    focalZones: ['bow arc', 'face profile', 'chest gem'],
    forbiddenFeatures: ['full realistic anatomy', 'crowded arrows/quiver details'],
  },
];
