import type { SilhouetteTemplate } from '../schema';

export const MONSTER_TEMPLATES: SilhouetteTemplate[] = [
  {
    id: 'monster_brute_horned',
    archetype: 'monster',
    subtype: 'brute',
    description: 'Heavy forward mass with horn or tusk accents.',
    poseRead: 'forward-leaning',
    symmetry: 'medium',
    shapeLanguage: ['bulk', 'horns', 'jaw wedge', 'thick upper mass'],
    anchors: [
      { id: 'head', x: 12, y: 8 },
      { id: 'jaw', x: 12, y: 12 },
      { id: 'horn-left', x: 9, y: 6 },
      { id: 'horn-right', x: 15, y: 6 },
    ],
    basePaths: ['bulk-body', 'horns', 'jaw', 'legs-or-base-mass'],
    focalZones: ['eyes', 'jaw opening', 'horn tips'],
    forbiddenFeatures: ['too many limbs', 'tiny teeth arrays'],
  },
  {
    id: 'monster_stalker_cloaked',
    archetype: 'monster',
    subtype: 'stalker',
    description: 'Predatory cloaked silhouette with narrowed focal zone.',
    poseRead: 'forward-leaning',
    symmetry: 'low',
    shapeLanguage: ['hooded void', 'knife-like diagonals', 'lurking lower sweep'],
    anchors: [
      { id: 'head', x: 12, y: 8 },
      { id: 'eyes', x: 12, y: 10 },
      { id: 'cloak', x: 11, y: 14 },
    ],
    basePaths: ['hood-void', 'cloak', 'arm-blade-or-claw'],
    focalZones: ['eye line', 'void opening', 'claw highlight'],
    forbiddenFeatures: ['heroic symmetry', 'clean noble posture'],
  },
  {
    id: 'monster_swarm_mask',
    archetype: 'monster',
    subtype: 'swarm',
    description: 'Mask-like central presence with fragmenting lower geometry.',
    poseRead: 'coiled',
    symmetry: 'high',
    shapeLanguage: ['mask', 'fragments', 'multiple implied forms'],
    anchors: [
      { id: 'mask', x: 12, y: 8 },
      { id: 'fragment-left', x: 8, y: 15 },
      { id: 'fragment-right', x: 16, y: 15 },
    ],
    basePaths: ['mask', 'fragment-cluster-left', 'fragment-cluster-right'],
    focalZones: ['mask eyes', 'fragment spread'],
    forbiddenFeatures: ['literal crowd of small monsters'],
  },
  {
    id: 'monster_caster_spines',
    archetype: 'monster',
    subtype: 'caster',
    description: 'Tall central figure with ritual spines and hostile magical aura.',
    poseRead: 'regal',
    symmetry: 'high',
    shapeLanguage: ['ritual staff', 'spines', 'orb or void chest'],
    anchors: [
      { id: 'head', x: 12, y: 7 },
      { id: 'staff', x: 15, y: 13 },
      { id: 'chest-void', x: 12, y: 12 },
    ],
    basePaths: ['head', 'torso', 'staff', 'spines'],
    focalZones: ['chest void', 'staff tip', 'eye line'],
    forbiddenFeatures: ['friendly halo reads', 'soft heroic curves'],
  },
  {
    id: 'monster_aberration_eye',
    archetype: 'monster',
    subtype: 'aberration',
    description: 'Central eye/orb distortion with broken radial geometry.',
    poseRead: 'coiled',
    symmetry: 'medium',
    shapeLanguage: ['orb', 'radial breaks', 'distortion rings'],
    anchors: [
      { id: 'eye', x: 12, y: 10 },
      { id: 'ring', x: 12, y: 10 },
      { id: 'lower-mass', x: 12, y: 16 },
    ],
    basePaths: ['orb-eye', 'broken-ring', 'lower-distortion'],
    focalZones: ['eye', 'ring rupture'],
    forbiddenFeatures: ['cartoon tentacle detail', 'too many small appendages'],
  },
];
