import type { ThemeProfile } from './schema';

export const THEME_PROFILES: ThemeProfile[] = [
  {
    id: 'cathedral',
    description: 'Leaded stained glass with gothic arches and jewel tones.',
    invariantRules: [
      'Use leaded segmentation, not painterly gradients.',
      'Keep one highlight family from top-left only.',
      'Favor arch, halo, shield, spire, and reliquary motifs.',
      'Do not let ornament overpower silhouette readability.',
    ],
    ornamentBias: ['cathedral_arch', 'sunburst_halo', 'arcane_ring'],
    segmentationBias: ['vertical_cathedral', 'radial_halo', 'shield_facets'],
    mapping: {
      heroPrimary: 'var(--hc-jewel-emerald-500)',
      heroSecondary: 'var(--hc-jewel-emerald-300)',
      monsterPrimary: 'var(--hc-jewel-amethyst-500)',
      monsterSecondary: 'var(--hc-jewel-amethyst-300)',
      bossPrimary: 'var(--hc-jewel-ruby-700)',
      bossSecondary: 'var(--hc-jewel-ruby-500)',
      lead: 'var(--hc-lead-iron-900)',
      highlight: 'var(--hc-glow-pearl)',
    },
  },
  {
    id: 'arcane',
    description: 'Mystic rings and circular faceting with magical geometry.',
    invariantRules: [
      'Keep strong silhouette center.',
      'Use glyph arcs and ring segmentation instead of arches.',
      'Avoid naturalistic detailing.',
    ],
    ornamentBias: ['arcane_ring', 'sunburst_halo'],
    segmentationBias: ['radial_halo', 'hex_lattice'],
    mapping: {
      heroPrimary: 'var(--hc-jewel-sapphire-500)',
      heroSecondary: 'var(--hc-jewel-sapphire-300)',
      monsterPrimary: 'var(--hc-jewel-amethyst-500)',
      monsterSecondary: 'var(--hc-jewel-amethyst-300)',
      bossPrimary: 'var(--hc-jewel-ruby-700)',
      bossSecondary: 'var(--hc-jewel-ruby-500)',
      lead: 'var(--hc-lead-iron-900)',
      highlight: 'var(--hc-glow-pearl)',
    },
  },
  {
    id: 'verdant',
    description: 'Organic faceting with vines, leaf cells, and floral geometry.',
    invariantRules: [
      'Silhouette remains primary.',
      'Curves can increase, but cell logic must remain explicit.',
      'Keep small-scale readability above ornament density.',
    ],
    ornamentBias: ['thorned_vines', 'sunburst_halo'],
    segmentationBias: ['vine_cells', 'shield_facets'],
    mapping: {
      heroPrimary: 'var(--hc-jewel-emerald-500)',
      heroSecondary: 'var(--hc-jewel-emerald-300)',
      monsterPrimary: 'var(--hc-jewel-ruby-500)',
      monsterSecondary: 'var(--hc-jewel-amber-300)',
      bossPrimary: 'var(--hc-jewel-ruby-700)',
      bossSecondary: 'var(--hc-jewel-ruby-500)',
      lead: 'var(--hc-lead-iron-900)',
      highlight: 'var(--hc-glow-pearl)',
    },
  },
  {
    id: 'mechanical',
    description: 'Panelized glass and segmented apertures with technical faceting.',
    invariantRules: [
      'Maintain lead-line clarity.',
      'Favor angular panel logic over free curves.',
      'Keep silhouettes readable before adding mechanical frame language.',
    ],
    ornamentBias: ['mechanical_aperture', 'arcane_ring'],
    segmentationBias: ['hex_lattice', 'vertical_cathedral'],
    mapping: {
      heroPrimary: 'var(--hc-jewel-pearl-500)',
      heroSecondary: 'var(--hc-jewel-sapphire-300)',
      monsterPrimary: 'var(--hc-jewel-ruby-500)',
      monsterSecondary: 'var(--hc-jewel-pearl-300)',
      bossPrimary: 'var(--hc-jewel-ruby-700)',
      bossSecondary: 'var(--hc-jewel-ruby-500)',
      lead: 'var(--hc-lead-iron-900)',
      highlight: 'var(--hc-glow-pearl)',
    },
  },
];
