// src/theme/tokens.ts
//
// AUTO-GENERATED from src/styles/tokens.css by tools/vite-plugin-tokens.ts.
// DO NOT edit by hand. Run `npm run dev` or `npm run verify:tokens` to regenerate.
//
// Source of truth: .claude/design/elysian-cathedral/palette.md

export const HC_TOKENS = {
  jewel: {
    sapphire: {
      100: '#cbd8f1',
      300: '#6e8ccb',
      500: '#2e4ba0',
      700: '#1a2e6e',
      900: '#0d1a46',
    },
    emerald: {
      100: '#c9e7d1',
      300: '#5fb079',
      500: '#1f7a46',
      700: '#0f5028',
      900: '#062e17',
    },
    ruby: {
      100: '#f1ccd4',
      300: '#d96a82',
      500: '#a1223c',
      700: '#6e102a',
      900: '#3a0517',
    },
    amber: {
      100: '#f6e7bc',
      300: '#e8bd59',
      500: '#c48a1f',
      700: '#8a5a10',
      900: '#4d2f04',
    },
    amethyst: {
      100: '#decde9',
      300: '#9570ba',
      500: '#5b3a8a',
      700: '#361e5b',
      900: '#1b0c30',
    },
    pearl: {
      100: '#f2f4f7',
      300: '#c9d2db',
      500: '#8a97a5',
      700: '#4a5460',
      900: '#232830',
    },
  },
  lead: {
    iron: {
      500: '#2e2838',
      700: '#1a1620',
      900: '#0e0c14',
    },
    gold: {
      500: '#b89142',
      700: '#8b6a2a',
      900: '#5a3f10',
    },
    silver: {
      500: '#8a95a2',
      700: '#5e6775',
    },
  },
  parchment: {
    50: '#fbf6e9',
    100: '#f4ebd3',
    300: '#e0d2ab',
    500: '#bfa979',
    700: '#7f6a3f',
  },
  shadow: {
    500: '#2e3d69',
    600: '#1e2b52',
    700: '#131d3e',
    800: '#0b1228',
    900: '#05080f',
  },
  glow: {
    amber: 'rgba(232, 189, 89, 0.55)',
    sapphire: 'rgba(110, 140, 203, 0.45)',
    emerald: 'rgba(95, 176, 121, 0.45)',
    ruby: 'rgba(217, 106, 130, 0.5)',
    pearl: 'rgba(242, 244, 247, 0.35)',
    shadow: 'rgba(5, 8, 15, 0.6)',
  },
  champion: {
    courage: {
      fill: 'var(--hc-jewel-emerald-500)',
      lead: 'var(--hc-lead-iron-700)',
      glow: 'var(--hc-glow-emerald)',
    },
    wisdom: {
      fill: 'var(--hc-jewel-sapphire-500)',
      lead: 'var(--hc-lead-silver-700)',
      glow: 'var(--hc-glow-sapphire)',
    },
    power: {
      fill: 'var(--hc-jewel-ruby-500)',
      lead: 'var(--hc-lead-gold-700)',
      glow: 'var(--hc-glow-ruby)',
    },
    sword: {
      fill: 'var(--hc-jewel-pearl-500)',
      lead: 'var(--hc-lead-iron-900)',
      glow: 'var(--hc-glow-pearl)',
    },
  },
  resource: {
    'shard-green': {
      gem: 'var(--hc-jewel-emerald-500)',
      lead: 'var(--hc-lead-iron-700)',
    },
    power: {
      gem: 'var(--hc-jewel-ruby-500)',
      lead: 'var(--hc-lead-gold-700)',
    },
    sword: {
      gem: 'var(--hc-jewel-pearl-500)',
      lead: 'var(--hc-lead-iron-900)',
    },
    heart: {
      gem: 'var(--hc-jewel-ruby-300)',
      lead: 'var(--hc-lead-gold-500)',
    },
    key: {
      gem: 'var(--hc-jewel-amber-500)',
      lead: 'var(--hc-lead-gold-700)',
    },
    shield: {
      gem: 'var(--hc-jewel-sapphire-500)',
      lead: 'var(--hc-lead-silver-700)',
    },
  },
  tier: {
    small: {
      glass: 'var(--hc-parchment-500)',
      lead: 'var(--hc-lead-iron-700)',
      cap: 'var(--hc-jewel-amber-300)',
    },
    medium: {
      glass: 'var(--hc-jewel-emerald-700)',
      lead: 'var(--hc-lead-gold-500)',
      cap: 'var(--hc-jewel-amber-500)',
    },
    big: {
      glass: 'var(--hc-jewel-sapphire-700)',
      lead: 'var(--hc-lead-gold-700)',
      cap: 'var(--hc-jewel-amber-300)',
    },
  },
  semantic: {
    'lead-gold-700-alpha-35': 'var(--hc-lead-gold-700-alpha-35)',
    'lead-iron-900-alpha-75': 'var(--hc-lead-iron-900-alpha-75)',
    'bg-app': 'var(--hc-bg-app)',
    'bg-panel': 'var(--hc-bg-panel)',
    'bg-parchment': 'var(--hc-bg-parchment)',
    'text-primary': 'var(--hc-text-primary)',
    'text-inverse': 'var(--hc-text-inverse)',
    'text-muted': 'var(--hc-text-muted)',
    'text-gold': 'var(--hc-text-gold)',
    'border-default': 'var(--hc-border-default)',
    'border-muted': 'var(--hc-border-muted)',
    'border-gold': 'var(--hc-border-gold)',
    'focus-ring': 'var(--hc-focus-ring)',
    scrim: 'var(--hc-scrim)',
    'font-display': 'var(--hc-font-display)',
    'font-body': 'var(--hc-font-body)',
    'font-numeric': 'var(--hc-font-numeric)',
    'text-px-6': 'var(--hc-text-px-6)',
    'text-px-7': 'var(--hc-text-px-7)',
    'text-px-8': 'var(--hc-text-px-8)',
    'text-px-9': 'var(--hc-text-px-9)',
    'text-px-10': 'var(--hc-text-px-10)',
    'text-px-11': 'var(--hc-text-px-11)',
    'text-xs': 'var(--hc-text-xs)',
    'text-sm': 'var(--hc-text-sm)',
    'text-base': 'var(--hc-text-base)',
    'text-lg': 'var(--hc-text-lg)',
    'text-xl': 'var(--hc-text-xl)',
    'text-2xl': 'var(--hc-text-2xl)',
    'text-3xl': 'var(--hc-text-3xl)',
    'text-4xl': 'var(--hc-text-4xl)',
    'text-display': 'var(--hc-text-display)',
    'line-xs': 'var(--hc-line-xs)',
    'line-sm': 'var(--hc-line-sm)',
    'line-base': 'var(--hc-line-base)',
    'line-lg': 'var(--hc-line-lg)',
    'line-xl': 'var(--hc-line-xl)',
    'line-2xl': 'var(--hc-line-2xl)',
    'line-3xl': 'var(--hc-line-3xl)',
    'line-4xl': 'var(--hc-line-4xl)',
    'line-display': 'var(--hc-line-display)',
    'line-tight': 'var(--hc-line-tight)',
    'line-normal': 'var(--hc-line-normal)',
    'line-loose': 'var(--hc-line-loose)',
    'font-weight-regular': 'var(--hc-font-weight-regular)',
    'font-weight-medium': 'var(--hc-font-weight-medium)',
    'font-weight-semibold': 'var(--hc-font-weight-semibold)',
    'font-weight-bold': 'var(--hc-font-weight-bold)',
    'font-weight-extrabold': 'var(--hc-font-weight-extrabold)',
    'font-weight-black': 'var(--hc-font-weight-black)',
    'weight-xs': 'var(--hc-weight-xs)',
    'weight-sm': 'var(--hc-weight-sm)',
    'weight-base': 'var(--hc-weight-base)',
    'weight-lg': 'var(--hc-weight-lg)',
    'weight-xl': 'var(--hc-weight-xl)',
    'weight-2xl': 'var(--hc-weight-2xl)',
    'weight-3xl': 'var(--hc-weight-3xl)',
    'weight-4xl': 'var(--hc-weight-4xl)',
    'weight-display': 'var(--hc-weight-display)',
    'tracking-tight': 'var(--hc-tracking-tight)',
    'tracking-normal': 'var(--hc-tracking-normal)',
    'tracking-banner': 'var(--hc-tracking-banner)',
    'tracking-wide': 'var(--hc-tracking-wide)',
    'tracking-wider': 'var(--hc-tracking-wider)',
    'tracking-chrome-sm': 'var(--hc-tracking-chrome-sm)',
    'tracking-chrome': 'var(--hc-tracking-chrome)',
    'tracking-chrome-md': 'var(--hc-tracking-chrome-md)',
    'tracking-chrome-wide': 'var(--hc-tracking-chrome-wide)',
    'tracking-chrome-lg': 'var(--hc-tracking-chrome-lg)',
    'tracking-chrome-extra': 'var(--hc-tracking-chrome-extra)',
    'tracking-chrome-max': 'var(--hc-tracking-chrome-max)',
  },
} as const;

export type HCTokens = typeof HC_TOKENS;
